name: Validate Maven Artifacts Bundling

on:
  push:
    branches:
      - main
      - release
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      MAVEN_PRIVATE_REPO_USERNAME: ${{ secrets.MAVEN_PRIVATE_REPO_USERNAME }}
      MAVEN_PRIVATE_REPO_PASSWORD: ${{ secrets.MAVEN_PRIVATE_REPO_PASSWORD }}
      MAVEN_PRIVATE_REPO_URL: ${{ secrets.MAVEN_PRIVATE_REPO_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven with settings.xml
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Build
        run: mvn clean install -s.mvn/settings.xml -DskipTests